import { NeonAuthUIProvider } from '@neondatabase/neon-js/auth/react';
import '@neondatabase/neon-js/ui/css';
import { authClient } from '@/lib/auth';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { TooltipProvider } from "@/components/ui/tooltip"
import { Toaster } from "@/components/ui/sonner"

import "./globals.css";
import StoreProvider from "@/lib/StoreProvider";
import ThemeInitializer from "@/lib/features/theme/ThemeInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      > 
      <NeonAuthUIProvider emailOTP authClient={authClient}>
        <StoreProvider>
          <ThemeInitializer />
          <TooltipProvider>
              <main>
              {children}
              <Toaster />
              </main>
          </TooltipProvider>
        </StoreProvider>
      </NeonAuthUIProvider>
      </body>
    </html>
  );
}
